[package]
name = "fe2o3-amqp-types"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_amqp = { version = "0.0.1", path = "../serde_amqp", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
ordered-float = { version = "2.7", features = ["serde"] }
serde_repr = "0.1"
trust-dns-resolver = "0.20"
