[workspace]
members = [
    # serde 
    "fe2o3-amqp-macros",
    "fe2o3-amqp",

    # frame transport
    "fe2o3-types",

    "fe2o3-engine",
    "fe2o3-amqp-ext",

    "examples/macro_expand"
]

exclude = [

]