[workspace]
members = [
    # serde 
    "serde_amqp_derive",
    "serde_amqp",

    # frame transport
    "fe2o3-amqp",
    "fe2o3-amqp-ext",
    "fe2o3-amqp-types",

    # examples
    "examples/macro_expand",
]

exclude = [
    "examples/protocol_test",
    "examples/sasl_connection",
    "examples/tls_connection",
    "examples/alternative_tls_connection",
    "examples/tls_sasl_connection",
    "examples/sender",
    "examples/receiver",
    "examples/listener",
    "examples/sasl_listener",
    "examples/tls_listener",
    "examples/alternative_tls_listener",
    "examples/tls_sasl_listener",
    "examples/txn_posting",
    "examples/txn_retirement",
    "examples/txn_enabled_listener",
]