[workspace]
members = [
    # serde 
    "serde_amqp_derive",
    "serde_amqp",

    # frame transport
    "fe2o3-types",

    "fe2o3-engine",
    "fe2o3-amqp-ext",

    "examples/macro_expand",
    "examples/protocol_test"
]

exclude = [

]