[package]
name = "serde_amqp_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dev-dependencies]
serde = { version = "1.0.127", features = ["derive"] }

[dependencies]
convert_case = "0.4.0"
darling = "0.13.0"
proc-macro2 = "1.0.28"
quote = "1.0.9"
syn = { version = "1.0.74", features = ["parsing", "derive"] } 
