[package]
name = "serde_amqp"
version = "0.0.1"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serde_amqp_derive]
version = "0.1.0"
path = "../serde_amqp_derive"

[dependencies]
ordered-float = { version = "2.7.0", features = ["serde"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_bytes = "0.11.5"
thiserror = "1.0.26"

chrono = { version = "0.4.19", features = ["serde"], optional = true }
uuid = { version = "0.8.2", features = ["serde"], optional = true }


