[package]
name = "serde_amqp"
version = "0.0.2"
edition = "2021"
description = "A serde implementation of AMQP1.0 protocol."
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/serde_amqp/"
homepage = "https://github.com/minghuaw/fe2o3-amqp"
repository = "https://github.com/minghuaw/fe2o3-amqp"
keywords = ["amqp", "serde"]
categories = ["parsing", "parser-implementations"]
readme = "Readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
all-features = true

[features]
default = []
# default = ["derive"]

derive = ["serde_amqp_derive"]

# [dev-dependencies]
# serde_amqp_derive = { version = "0.0.1", path = "../serde_amqp_derive" }

[dependencies.serde_amqp_derive]
version = "0.0.1"
# path = "../serde_amqp_derive"
optional = true

[dependencies]
ordered-float = { version = "2.7", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
thiserror = "1"
bytes = "1"

# Optinal dependencies
chrono = { version = "0.4", features = ["serde"], optional = true }
uuid = { version = "0.8", features = ["serde"], optional = true }
