[tasks.test]
command = "cargo"
args = ["test", "--features", "derive extensions"]

[tasks.expand]
command = "cargo"
args = ["expand", "--test", "derive", "--features", "derive"]

[tasks.doctest]
args = [
  "doc",
  "--no-deps",
  "--all-features",
  "--open",
  "-Z",
  "unstable-options",
  "--config",
  "build.rustdocflags=[\"--cfg\", \"docsrs\"]",
]
command = "cargo"
toolchain = "nightly"