extend = "../Makefile.toml"

[tasks.test]
command = "cargo"
args = ["test", "--features", "derive extensions"]

[tasks.expand]
command = "cargo"
args = ["expand", "--test", "derive", "--features", "derive"]