[package]
name = "fe2o3-amqp-ws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.21"
tokio = "1.20.1"
tokio-tungstenite = "0.17.2"
tungstenite = "0.17.3"
