[package]
name = "fe2o3-amqp-ext"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_amqp = { version = "0.0.1", path = "../serde_amqp" }
fe2o3-amqp-types = { version = "0.1.0", path = "../fe2o3-amqp-types" }
