[package]
name = "fe2o3-amqp-ext"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fe2o3-amqp = { version = "0.0.1", path = "../fe2o3-amqp" }
fe2o3-types = { version = "0.1.0", path = "../fe2o3-types" }
