[package]
name = "fe2o3-amqp"
version = "0.0.1"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.fe2o3-amqp-macros]
path = "../fe2o3-amqp-macros"
version = "0.1.0"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
ordered-float = { version = "2.7.0", features = ["serde"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_bytes = "0.11.5"
uuid = { version = "0.8.2", features = ["serde"] }


