[package]
name = "fe2o3-amqp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tokio = { version = "1.11.0", features = ["rt", "macros"] }
tokio-test = { version = "0.4.2" }

[dependencies.serde_amqp]
version = "0.0.1"
path = "../serde_amqp"

[dependencies.fe2o3-amqp-types]
version = "0.1.0"
path = "../fe2o3-amqp-types"

[dependencies]
bytes = "1.1.0"
tokio = { version = "1.11.0", features = ["io-util", "net", "rt"] }
tokio-util = { version = "0.6.8", features = ["codec"] }
thiserror = "1.0.28"
serde = "1.0.130"
erased-serde = "0.3.16"
futures-util = { version = "0.3.17", features = ["sink"] }
pin-project-lite = "0.2.7"
url = "2.2.2"
slab = "0.4.4"
tokio-stream = { version = "0.1.7", features = ["time"] }
async-trait = "0.1.51"
