[package]
name = "fe2o3-amqp"
version = "0.0.1"
edition = "2021"
description = "An implementation of AMQP1.0 protocol based on serde and tokio"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/fe2o3-amqp/"
homepage = "https://github.com/minghuaw/fe2o3-amqp"
repository = "https://github.com/minghuaw/fe2o3-amqp"
keywords = ["amqp", "serde", "tokio"]
readme = "Readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
tokio-test = { version = "0.4" }
testcontainers = "0.12"

[dependencies]
serde_amqp = "0.0.3"
fe2o3-amqp-types = "0.0.4"
# fe2o3-amqp-types = { version = "0.0.3", path = "../fe2o3-amqp-types" }

bytes = "1"
tokio = { version = "1", features = ["io-util", "net", "rt", "macros"] }
tokio-util = { version = "0.7", features = ["codec"] }
thiserror = "1"
serde = "1"
erased-serde = "^0.3.16"
futures-util = { version = "0.3", features = ["sink"] }
pin-project-lite = "0.2"
url = "2"
slab = "0.4"
tokio-stream = { version = "0.1", features = ["time"] }
async-trait = "0.1"
crossbeam = "0.8"
tokio-rustls = "0.23"
rustls = "0.20"
serde_bytes = "0.11"
tracing = "0.1"
