[package]
name = "fe2o3-amqp"
version = "0.0.17"
edition = "2021"
description = "An implementation of AMQP1.0 protocol based on serde and tokio"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/fe2o3-amqp/"
homepage = "https://github.com/minghuaw/fe2o3-amqp"
repository = "https://github.com/minghuaw/fe2o3-amqp"
keywords = ["amqp", "serde", "tokio"]
readme = "Readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
# default = []

## dev defaults
# default = [
#     "acceptor",
#     "rustls",
#     "native-tls",
#     "transaction",
# ]

transaction = ["fe2o3-amqp-types/transaction", "uuid"]

# TLS related features
rustls = ["tokio-rustls", "librustls", "webpki-roots"]
native-tls = ["tokio-native-tls", "libnative-tls"]

# Listener implementation
acceptor = []

[dev-dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
tokio-test = { version = "0.4" }
testcontainers = "0.14.0"

[dependencies]
serde_amqp = "0.0.8"
# serde_amqp = { version = "0.0.8", path = "../serde_amqp" }
fe2o3-amqp-types = "0.0.21"
# fe2o3-amqp-types = { version = "0.0.21", path = "../fe2o3-amqp-types" }

bytes = "1"
tokio = { version = "^1.16.1", features = ["io-util", "net", "rt", "macros"] }
tokio-util = { version = "0.7", features = ["codec"] }
thiserror = "1"
serde = "1"
erased-serde = "^0.3.16"
futures-util = { version = "0.3", features = ["sink"] }
pin-project-lite = "0.2"
url = "2"
slab = "0.4"
tokio-stream = { version = "0.1", features = ["time"] }
async-trait = "0.1"
serde_bytes = "0.11"
tracing = "0.1"

# Optional deps
tokio-rustls = { version = "0.23", optional = true }
librustls = { package = "rustls", version = "0.20", optional = true }
webpki-roots = { version = "0.22", optional = true }
tokio-native-tls = { version = "0.3", optional = true }
libnative-tls = { package = "native-tls", version = "0.2.8", optional = true }
uuid = { version = "1.1.2", features = ["v4"], optional = true }
