[package]
name = "fe2o3-amqp"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
tokio-test = { version = "0.4" }
testcontainers = "0.12"

# [dependencies.serde_amqp]
# version = "0.0.1"
# path = "../serde_amqp"

# [dependencies.fe2o3-amqp-types]
# version = "0.0.2"
# path = "../fe2o3-amqp-types"

[dependencies]
serde_amqp = "0.0.2"
fe2o3-amqp-types = "0.0.3"

bytes = "1"
tokio = { version = "1", features = ["io-util", "net", "rt"] }
tokio-util = { version = "0.7", features = ["codec"] }
thiserror = "1"
serde = "1"
erased-serde = "^0.3.16"
futures-util = { version = "0.3", features = ["sink"] }
pin-project-lite = "0.2"
url = "2"
slab = "0.4"
tokio-stream = { version = "0.1", features = ["time"] }
async-trait = "0.1"
crossbeam = "0.8"
tokio-rustls = "0.23"
rustls = "0.20"
serde_bytes = "0.11"
tracing = "0.1"
