[tasks.doctest]
args = [
  "doc",
  "--no-deps",
  "--all-features",
  "--open",
  "-Z",
  "unstable-options",
  "--config",
  "build.rustdocflags=[\"--cfg\", \"docsrs\"]",
]
command = "cargo"
toolchain = "nightly"

[tasks.feature_check]
dependencies = [
  "check_feature_acceptor",
  "check_feature_rustls",
  "check_feature_nativetls",
  "check_feature_transaction",
  "check_feature_group1",
  "check_feature_group2",
  "check_feature_group3",
  "check_feature_group4",
  "check_all_features",
]

[tasks.check_all_features]
args = [
  "check",
  "--all-features",
]
command = "cargo"
toolchain = "stable"

[tasks.check_feature_acceptor]
args = [
  "check",
  "--no-default-features",
  "--features",
  "acceptor",
]
command = "cargo"
toolchain = "stable"

[tasks.check_feature_rustls]
args = [
  "check",
  "--no-default-features",
  "--features",
  "rustls",
]
command = "cargo"
toolchain = "stable"

[tasks.check_feature_nativetls]
args = [
  "check",
  "--no-default-features",
  "--features",
  "native-tls",
]
command = "cargo"
toolchain = "stable"

[tasks.check_feature_transaction]
args = [
  "check",
  "--no-default-features",
  "--features",
  "transaction",
]
command = "cargo"
toolchain = "stable"

[tasks.check_feature_group1]
args = [
  "check",
  "--no-default-features",
  "--features",
  "rustls, transaction",
]
command = "cargo"
toolchain = "stable"

[tasks.check_feature_group2]
args = [
  "check",
  "--no-default-features",
  "--features",
  "native-tls, transaction",
]
command = "cargo"
toolchain = "stable"

[tasks.check_feature_group3]
args = [
  "check",
  "--no-default-features",
  "--features",
  "acceptor, rustls, transaction",
]
command = "cargo"
toolchain = "stable"

[tasks.check_feature_group4]
args = [
  "check",
  "--no-default-features",
  "--features",
  "acceptor, native-tls, transaction",
]
command = "cargo"
toolchain = "stable"
