[config]
skip_core_tasks = true

[tasks.check]
script = '''
# ignored examples
protocol_test="./protocol_test"
wasm32_in_browser="./wasm32-in-browser"

for entry in ./*
do
    if [ "$entry" == "$protocol_test" ]; then
        echo "Ignored"
    elif [ "$entry" == "$wasm32_in_browser" ]; then
        echo "Ignored"
    elif [ -d "$entry" ]; then
        cargo update
        cargo check --manifest-path "$entry/Cargo.toml" --all-targets --all-features
    fi
done
'''